### 🤖 Guía de Asistencia con IA: Estandarización y Codificación de Variables (Feature Engineering)

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Elegir Encoding**: Pídele consejo: *'Tengo una variable categórica 'Ciudad' con 30 valores únicos. ¿Es mejor usar One-Hot Encoding o Target Encoding? ¿Cómo lo hago con scikit-learn?'*.
- **Cuándo escalar**: Pregúntale: *'¿Por qué los modelos basados en distancia (como KNN o SVM) necesitan que los datos estén estandarizados, y por qué a los árboles de decisión no les afecta?'*.

# Programa Ingenias+ Data Science

Ya dijimos previamente que un proyecto de data science tiene varias etapas:

1. Recolección de Datos
2. Exploración y Procesamiento de los datos
3. Modelado
4. Puesta en Producción

En la clase anterior, hicimos el analisis exploratorio de los datos y pudimos observar el tipo de datos que teniamos. Pudimos hacernos preguntas y ver algunos patrones. Todo ese conocimiento que adquirimos es útil para llevar a cabo la próxima parte de esta etapa: el procesamiento de los datos.

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

<font size=5>  🚀 Procesamiento de datos 👩🏽‍💻</font>

Una vez que visualizamos y exploramos el dataset tenemos una idea de como lucen nuestros datos. Es por eso que ahora debemos empezar a preparar nuestros datos para los siguientes pasos según lo que aprendimos de ellos y las preguntas que nos planteamos.

In [24]:
blackfriday = pd.read_csv('https://raw.githubusercontent.com/BelenUrdangarin/Entregables---Urdangarin/refs/heads/main/black_friday_reducido.csv', sep=';')
blackfriday.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0
5,1000005,P00251242,M,26.0,20.0,A,1,1,5,11.0,NaN,5254.0
6,1000006,P00190242,F,53.0,9.0,A,1,0,4,5.0,NaN,2079.0
7,1000008,P00249542,M,27.0,12.0,C,4,1,1,5.0,15.0,19614.0
8,1000008,P00214442,M,33.0,12.0,C,4,1,8,NaN,NaN,5982.0
9,1000009,P00135742,M,30.0,17.0,C,0,0,6,8.0,NaN,16662.0

#### 1) TRANSFORMACION DE VARIABLES

- La mayoría de los algoritmos de machine learning no admiten `strings` como variables y requieren que las variables sean numericas. Por ese motivo, es necesario convertir las variables categoricas en su representación numerica. Para esto hay varias opciones que iremos viendo.

**`LabelEncoder()`**

In [25]:
from sklearn.preprocessing import LabelEncoder 
# Con Label encoder lo que hacemos es cambiar una categoria que tenia nombre por ejemplo de ciudades en que las ponga 0,1,2,3, ect

In [26]:
test_encoder = LabelEncoder() #Ejecutamos la función

In [27]:
# IMPORTATE: mal porque estoy encodeando una variable predictiva
# blackfriday.loc[:, 'City_Category'] = test_encoder.fit_transform(blackfriday['City_Category'])

# Correccion

¿Porque ocurre esto?

Esto ocurre porque, aunque se usó "LabelEncoder" con "City_Category", esta herramienta de scikit-learn esta diseñada principalmente para codificar las variables **target** (las que vamos a predecir, usualmente en una columna), no los **features** (osea la variables predictivas para entrenar al entorno)

### Solucion
Para varaibles predictivas categóricas (com"o "City_Category"), la principal recomendacion es utilizar **"OneHotEncoder"** si no tiene orden y si tiene usaremos **"OrdinalEncoder"**.

In [28]:
# Resolución correcta: Utilizar OrdinalEncoder o OneHorEncoder para Features
from sklearn.preprocessing import OrdinalEncoder

ord_encoder = OrdinalEncoder()
blackfriday[['City_Categoty_Encoded']]=ord_encoder.fit_transform(blackfriday[['City_Category']])
blackfriday.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,City_Categoty_Encoded
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0,0.0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0,0.0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0,0.0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0,0.0
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0,1.0

In [29]:
blackfriday.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,City_Categoty_Encoded
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0,0.0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0,0.0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0,0.0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0,0.0
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0,1.0
5,1000005,P00251242,M,26.0,20.0,A,1,1,5,11.0,NaN,5254.0,0.0
6,1000006,P00190242,F,53.0,9.0,A,1,0,4,5.0,NaN,2079.0,0.0
7,1000008,P00249542,M,27.0,12.0,C,4,1,1,5.0,15.0,19614.0,2.0
8,1000008,P00214442,M,33.0,12.0,C,4,1,8,NaN,NaN,5982.0,2.0
9,1000009,P00135742,M,30.0,17.0,C,0,0,6,8.0,NaN,16662.0,2.0

**`get_dummies()`** Corregido

In [30]:
#falta el drop first y si quiero 1 y 0 el dtype int
pd.get_dummies(blackfriday["Gender"])

            F      M
0        True  False
1       False  False
2        True  False
3       False   True
4       False   True
...       ...    ...
188318  False   True
188319  False   True
188320  False   True
188321  False   True
188322  False   True

[188323 rows x 2 columns]

# Problema con get_dummies()
En este casos pd.get_dummies por defecto devuelve True/False (booleanos) en versiones recientes de Pandas y crea una columna por cada categoría. Esto genera "multicolinealidad" (osea dos columnas del dataset están aportando exactamente la misma informacion al modelo)

In [31]:
dummies_gender=pd.get_dummies(blackfriday["Gender"], drop_first=True, dtype=int)
display(dummies_gender.head())

   M
0  0
1  0
2  0
3  1
4  1

In [32]:
# Para unirlo al dataframe original (como se intentó hacer):
# Nota: get_dummies con drop_first=True sobre Gender (que tiene M, F y NaNs)
# devolverá solo una columna (por ejemplo 'M'). 
# El enfoque original creaba dos columnas ('female', 'male') sin drop_first.
# Mantendremos el enfoque original de agregar dos columnas, pero casteadas a int.
blackfriday[['famale','male']]=pd.get_dummies(blackfriday["Gender"], dtype=int)
blackfriday.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,City_Categoty_Encoded,famale,male
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0,0.0,1,0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0,0.0,0,0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0,0.0,1,0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0,0.0,0,1
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0,1.0,0,1

**`OneHotEncoder()`**

In [33]:
# ERROR AQUI: si hago drop first despues no puede pedir categorias
# from sklearn.preprocessing import OneHotEncoder
# blackfriday['Gender'].unique()
# gender_encoder = OneHotEncoder() 
# gender_encoder.fit_transform(blackfriday[['Gender']]).toarray()
# gender_encoder.categories_
# niveles = gender_encoder.categories_[0].tolist() ##get_features_name_out
# gender_encoder.categories_
# one_hot_gender = pd.DataFrame(gender_encoder.fit_transform(blackfriday[['Gender']]).toarray(), columns=niveles)
# one_hot_gender
# new_df = pd.concat([blackfriday, one_hot_gender], axis=1)
# new_df.head()

In [34]:
from sklearn.preprocessing import OneHotEncoder

# Vemos los valores únicos: array(['F', nan, 'M'], dtype=object)
print(blackfriday['Gender'].unique())

# ANOTACIÓN CORREGIDA: si hago drop first despues no puede pedir categorias
# El problema: Si usamos drop='first' en OneHotEncoder, elimina una categoría para evitar colinealidad.
# Si luego hacemos `encoder.categories_`, nos mostrará TODAS las categorías originales que aprendió,
# y al intentar mapear los nombres de las columnas (con len=3) a la matriz transformada (con len=2), fallará.
# La solución: Usar el método oficial `get_feature_names_out()` en lugar de intentar extraer a mano `.categories_[0].tolist()`.

# RESOLUCIÓN CORRECTA:
# 1. Tratamos los valores NaN antes (o usamos handle_unknown)
# Para este ejemplo, llenaremos los nulos con 'Unknown' momentáneamente o usamos un imputador.
# Vamos a seguir la lógica original pero de forma robusta.

gender_encoder_robust = OneHotEncoder(sparse_output=False, drop='first') # sparse_output en versiones nuevas de sklearn

# Ajustamos y transformamos (OJO: Gender tiene NaNs, sklearn puede quejarse si no los manejamos, 
# pero asumiremos que el df está limpio o llenamos los nulos con 'Desconocido')
blackfriday['Gender_Filled'] = blackfriday['Gender'].fillna('Unknown')
matriz_one_hot = gender_encoder_robust.fit_transform(blackfriday[['Gender_Filled']])

# Obtenemos los nombres de las columnas correctamente generados
niveles_correctos = gender_encoder_robust.get_feature_names_out(['Gender_Filled'])

# Creamos el DataFrame
one_hot_gender_df = pd.DataFrame(matriz_one_hot, columns=niveles_correctos)

# Unimos con el dataset original
new_df = pd.concat([blackfriday, one_hot_gender_df], axis=1)
display(new_df.head())

<StringArray>
['F', nan, 'M']
Length: 3, dtype: str

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,City_Categoty_Encoded,famale,male,Gender_Filled,Gender_Filled_M,Gender_Filled_Unknown
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0,0.0,1,0,F,0.0,0.0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0,0.0,0,0,Unknown,0.0,1.0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0,0.0,1,0,F,0.0,0.0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0,0.0,0,1,M,1.0,0.0
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0,1.0,0,1,M,1.0,0.0

**`binning`**

In [35]:
print(blackfriday.Age.min())
print(blackfriday.Age.max())

14.0
74.0

In [36]:
# Nos asguramos de que sea numérica (el código original lo hace bien)
blackfriday["Age"] = pd.to_numeric(blackfriday["Age"], errors='coerce')

In [37]:
# Definimos los cortes (bins) y las etiquetas (labels)
bin_age = [10, 17, 70, 80]
labels = ["Adolescente", "Adulto", "Anciano"]

# Aplicamos la categorización
age_categories = pd.cut(blackfriday["Age"], bins=bin_age, labels=labels)
display(age_categories.head())

0    Adolescente
1    Adolescente
2    Adolescente
3         Adulto
4         Adulto
Name: Age, dtype: category
Categories (3, str): ['Adolescente' < 'Adulto' < 'Anciano']

In [38]:
age_categories

0         Adolescente
1         Adolescente
2         Adolescente
3              Adulto
4              Adulto
             ...
188318         Adulto
188319         Adulto
188320         Adulto
188321         Adulto
188322         Adulto
Name: Age, Length: 188323, dtype: category
Categories (3, str): ['Adolescente' < 'Adulto' < 'Anciano']